# Prototype launcher: save and validate a token, start FastAPI, then open RCAIDE.
$ErrorActionPreference = "Stop"

# Resolve every path from this script so it works from any PowerShell directory.
$projectRoot = $PSScriptRoot
$pythonExe = Join-Path (Split-Path $projectRoot -Parent) ".venv\Scripts\python.exe"
$tokenFile = Join-Path $projectRoot ".rcaide-agent-token.dat"
$serviceUrl = "http://127.0.0.1:8765"
# Keep the process handle so the finally block can always stop the backend.
$backendProcess = $null

# Fail early with a clear message instead of reporting missing Python packages.
if (-not (Test-Path -LiteralPath $pythonExe)) {
    throw "RCAIDE Python was not found at: $pythonExe"
}

function Read-RCAIDEToken {
    # Reuse the encrypted token after the first successful launcher run.
    # SecureString serialization uses Windows DPAPI rather than plaintext storage.
    if (Test-Path -LiteralPath $tokenFile) {
        try {
            $encrypted = (Get-Content -LiteralPath $tokenFile -Raw).Trim().TrimStart([char]0xFEFF)
            return ConvertTo-SecureString $encrypted
        }
        catch {
            # A DPAPI token copied from another user or PC cannot be decrypted.
            Remove-Item -LiteralPath $tokenFile -Force
        }
    }

    # Read-Host hides the token while it is pasted into the terminal.
    Write-Host "Copy your GitHub Models token, then paste it below."
    $secureToken = Read-Host "GitHub Models token" -AsSecureString
    # ConvertFrom-SecureString writes DPAPI ciphertext, not the original token.
    $secureToken | ConvertFrom-SecureString | Set-Content -LiteralPath $tokenFile
    return $secureToken
}

try {
    Set-Location -LiteralPath $projectRoot
    $secureToken = Read-RCAIDEToken
    # Uvicorn receives the plaintext token only through its process environment.
    $credential = [Net.NetworkCredential]::new("", $secureToken)
    $env:GITHUB_MODELS_TOKEN = $credential.Password

    # Reject common paste mistakes before making a network request.
    if (-not $env:GITHUB_MODELS_TOKEN.StartsWith("github_pat_")) {
        Remove-Item -LiteralPath $tokenFile -Force -ErrorAction SilentlyContinue
        throw "That does not look like a fine-grained GitHub token. Run this launcher again and paste the token generated by GitHub Models."
    }

    # Validate both the token and its Models: Read-only permission.
    Write-Host "Checking GitHub Models access..."
    $headers = @{
        Accept = "application/vnd.github+json"
        Authorization = "Bearer $env:GITHUB_MODELS_TOKEN"
        "X-GitHub-Api-Version" = "2022-11-28"
    }
    try {
        $modelCatalog = Invoke-RestMethod "https://models.github.ai/catalog/models" -Headers $headers
    }
    catch {
        # Remove a rejected token so the next run prompts for a replacement.
        Remove-Item -LiteralPath $tokenFile -Force -ErrorAction SilentlyContinue
        throw "GitHub rejected the token. Confirm Models: Read-only, copy the current token, and run this launcher again."
    }

    # Select the first supported model, favoring the lower-cost prototype model.
    $preferredModels = @(
        "openai/gpt-4.1-mini",
        "openai/gpt-4.1",
        "microsoft/Phi-4-mini-instruct"
    )
    $selectedModel = $preferredModels |
        Where-Object { $modelCatalog.id -contains $_ } |
        Select-Object -First 1
    if (-not $selectedModel) {
        throw "None of the RCAIDE prototype models are currently available in your GitHub Models catalog."
    }
    $env:RCAIDE_GITHUB_MODEL = $selectedModel

    Write-Host "Token accepted. Using $selectedModel."
    Write-Host "Starting the RCAIDE AI service..."
    # Run FastAPI without opening another terminal window.
    $backendProcess = Start-Process -FilePath $pythonExe `
        -ArgumentList @("-m", "uvicorn", "agent_server.app:app", "--host", "127.0.0.1", "--port", "8765") `
        -WorkingDirectory $projectRoot -WindowStyle Hidden -PassThru

    # Wait for /health before opening the GUI so its first request cannot race
    # against Uvicorn startup.
    $ready = $false
    for ($attempt = 0; $attempt -lt 30; $attempt++) {
        if ($backendProcess.HasExited) { break }
        try {
            $health = Invoke-RestMethod "$serviceUrl/health" -TimeoutSec 1
            if ($health.status -eq "ok") {
                $ready = $true
                break
            }
        }
        catch {
            Start-Sleep -Milliseconds 400
        }
    }
    if (-not $ready) {
        throw "The RCAIDE AI service could not start."
    }

    # Tell the desktop client which local API instance to call.
    $env:RCAIDE_AGENT_SERVICE_URL = $serviceUrl
    Write-Host "Opening RCAIDE. The AI assistant is ready."
    & $pythonExe (Join-Path $projectRoot "main.py")
}
catch {
    # Convert setup failures into a short, visible launcher message.
    Write-Host ""
    Write-Host $_.Exception.Message -ForegroundColor Red
    Read-Host "Press Enter to close"
    exit 1
}
finally {
    # Never leave the plaintext credential in this PowerShell environment.
    $env:GITHUB_MODELS_TOKEN = $null
    # Closing the GUI also closes the hidden backend started by this launcher.
    if ($backendProcess -and -not $backendProcess.HasExited) {
        Stop-Process -Id $backendProcess.Id -Force -ErrorAction SilentlyContinue
    }
}
