from tabs.analysis.frames.default_frame import DefaultFrame
from tabs.analysis.frames.aerodynamics_frame import AerodynamicsFrame
from tabs.analysis.frames.atmosphere_frame import AtmosphereFrame
from tabs.analysis.frames.costs_frame import CostsFrame
from tabs.analysis.frames.energy_frame import EnergyFrame
from tabs.analysis.frames.noise_frame import NoiseFrame
from tabs.analysis.frames.planets_frame import PlanetsFrame
from tabs.analysis.frames.propulsion_frame import PropulsionFrame
from tabs.analysis.frames.stability_frame import StabilityFrame
from tabs.analysis.frames.weights_frame import WeightsFrame