from tabs.analysis.widgets.analysis_data_widget import AnalysisDataWidget
from tabs.analysis.widgets.aerodynamics_widget import AerodynamicsWidget
from tabs.analysis.widgets.atmosphere_widget import AtmosphereWidget
from tabs.analysis.widgets.costs_widget import CostsWidget
from tabs.analysis.widgets.energy_widget import EnergyWidget
from tabs.analysis.widgets.noise_widget import NoiseWidget
from tabs.analysis.widgets.planets_widget import PlanetsWidget
from tabs.analysis.widgets.propulsion_widget import PropulsionWidget
from tabs.analysis.widgets.stability_widget import StabilityWidget
from tabs.analysis.widgets.weights_widget import WeightsWidget
from tabs.analysis.widgets.geometry_widget import GeometryWidget